language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 1.8.7
script: "bundle exec rake spec"
env:
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=2.7.18
  - PUPPET_VERSION=3.0.1
matrix:
  allow_failures:
    - env: PUPPET_VERSION=3.0.1
