name          'garethr-iaas'
version       '0.0.2'
author        'garethr'
license       'Apache License, Version 2.0'
summary       'Experiment with types and providers to orcestrate infrastructure services'
project_page  'https://github.com/garethr/garethr-iaas'
